# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.webhook_submission_created_event_relationships_resource_data import WebhookSubmissionCreatedEventRelationshipsResourceData

class TestWebhookSubmissionCreatedEventRelationshipsResourceData(unittest.TestCase):
    """WebhookSubmissionCreatedEventRelationshipsResourceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookSubmissionCreatedEventRelationshipsResourceData:
        """Test WebhookSubmissionCreatedEventRelationshipsResourceData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookSubmissionCreatedEventRelationshipsResourceData`
        """
        model = WebhookSubmissionCreatedEventRelationshipsResourceData()
        if include_optional:
            return WebhookSubmissionCreatedEventRelationshipsResourceData(
                type = 'submission',
                id = ''
            )
        else:
            return WebhookSubmissionCreatedEventRelationshipsResourceData(
                type = 'submission',
                id = '',
        )
        """

    def testWebhookSubmissionCreatedEventRelationshipsResourceData(self):
        """Test WebhookSubmissionCreatedEventRelationshipsResourceData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
