# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.create_comment_request_data import CreateCommentRequestData

class TestCreateCommentRequestData(unittest.TestCase):
    """CreateCommentRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCommentRequestData:
        """Test CreateCommentRequestData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCommentRequestData`
        """
        model = CreateCommentRequestData()
        if include_optional:
            return CreateCommentRequestData(
                type = 'comment',
                attributes = bugcrowd_client.models.create_comment_request_data_attributes.CreateCommentRequest_data_attributes(
                    body = '', 
                    visibility_scope = 'everyone', ),
                relationships = {"submission":{"data":{"id":{"$ref":"#/general_helpers/ValidUUID"},"type":"submission"}}}
            )
        else:
            return CreateCommentRequestData(
                type = 'comment',
                attributes = bugcrowd_client.models.create_comment_request_data_attributes.CreateCommentRequest_data_attributes(
                    body = '', 
                    visibility_scope = 'everyone', ),
                relationships = {"submission":{"data":{"id":{"$ref":"#/general_helpers/ValidUUID"},"type":"submission"}}},
        )
        """

    def testCreateCommentRequestData(self):
        """Test CreateCommentRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
