# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.cvss_vector import CvssVector

class TestCvssVector(unittest.TestCase):
    """CvssVector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CvssVector:
        """Test CvssVector
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CvssVector`
        """
        model = CvssVector()
        if include_optional:
            return CvssVector(
                id = '',
                type = 'cvss_vector',
                links = bugcrowd_client.models.self_link.SelfLink(
                    self = '', ),
                attributes = bugcrowd_client.models.cvss_vector_attributes.CvssVector_attributes(
                    attack_complexity = 'H', 
                    attack_vector = 'N', 
                    authorization_scope = 'U', 
                    availability_impact = 'H', 
                    confidentiality_impact = 'H', 
                    integrity_impact = 'H', 
                    privileges_required = 'H', 
                    score = 1.337, 
                    user_interaction = 'N', 
                    version = 2, ),
                relationships = None
            )
        else:
            return CvssVector(
                id = '',
                type = 'cvss_vector',
        )
        """

    def testCvssVector(self):
        """Test CvssVector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
