# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.create_credential_request_data import CreateCredentialRequestData

class TestCreateCredentialRequestData(unittest.TestCase):
    """CreateCredentialRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCredentialRequestData:
        """Test CreateCredentialRequestData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCredentialRequestData`
        """
        model = CreateCredentialRequestData()
        if include_optional:
            return CreateCredentialRequestData(
                type = 'credential',
                attributes = bugcrowd_client.models.attributes.attributes(),
                relationships = bugcrowd_client.models.create_credential_request_data_relationships.CreateCredentialRequest_data_relationships(
                    credential_bucket = bugcrowd_client.models.credential_bucket_not_nullable.CredentialBucketNotNullable(
                        data = bugcrowd_client.models.credential_bucket_not_nullable_data.CredentialBucketNotNullable_data(
                            id = '', 
                            type = 'credential_bucket', ), ), 
                    user = bugcrowd_client.models.user_not_nullable.UserNotNullable(
                        data = bugcrowd_client.models.user_not_nullable_data.UserNotNullable_data(
                            id = '', 
                            type = 'user', ), ), )
            )
        else:
            return CreateCredentialRequestData(
                type = 'credential',
                attributes = bugcrowd_client.models.attributes.attributes(),
                relationships = bugcrowd_client.models.create_credential_request_data_relationships.CreateCredentialRequest_data_relationships(
                    credential_bucket = bugcrowd_client.models.credential_bucket_not_nullable.CredentialBucketNotNullable(
                        data = bugcrowd_client.models.credential_bucket_not_nullable_data.CredentialBucketNotNullable_data(
                            id = '', 
                            type = 'credential_bucket', ), ), 
                    user = bugcrowd_client.models.user_not_nullable.UserNotNullable(
                        data = bugcrowd_client.models.user_not_nullable_data.UserNotNullable_data(
                            id = '', 
                            type = 'user', ), ), ),
        )
        """

    def testCreateCredentialRequestData(self):
        """Test CreateCredentialRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
