# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.create_access_grant_response import CreateAccessGrantResponse

class TestCreateAccessGrantResponse(unittest.TestCase):
    """CreateAccessGrantResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccessGrantResponse:
        """Test CreateAccessGrantResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccessGrantResponse`
        """
        model = CreateAccessGrantResponse()
        if include_optional:
            return CreateAccessGrantResponse(
                data = bugcrowd_client.models.access_grant.AccessGrant(
                    id = '', 
                    type = 'access_grant', 
                    links = bugcrowd_client.models.self_link.SelfLink(
                        self = '', ), 
                    attributes = bugcrowd_client.models.access_grant_attributes.AccessGrant_attributes(
                        role = '', ), 
                    relationships = bugcrowd_client.models.access_grant_relationships.AccessGrant_relationships(
                        grantee = bugcrowd_client.models.single_relationship.SingleRelationship(
                            links = bugcrowd_client.models.single_relationship_links.SingleRelationshipLinks(
                                related = bugcrowd_client.models.single_relationship_links_related.SingleRelationshipLinks_related(
                                    href = '', ), ), 
                            data = bugcrowd_client.models.basic_object.BasicObject(
                                id = '', 
                                type = '', ), ), 
                        resource = bugcrowd_client.models.single_relationship.SingleRelationship(
                            links = bugcrowd_client.models.single_relationship_links.SingleRelationshipLinks(
                                related = bugcrowd_client.models.single_relationship_links_related.SingleRelationshipLinks_related(
                                    href = '', ), ), 
                            data = bugcrowd_client.models.basic_object.BasicObject(
                                id = '', 
                                type = '', ), ), ), )
            )
        else:
            return CreateAccessGrantResponse(
                data = bugcrowd_client.models.access_grant.AccessGrant(
                    id = '', 
                    type = 'access_grant', 
                    links = bugcrowd_client.models.self_link.SelfLink(
                        self = '', ), 
                    attributes = bugcrowd_client.models.access_grant_attributes.AccessGrant_attributes(
                        role = '', ), 
                    relationships = bugcrowd_client.models.access_grant_relationships.AccessGrant_relationships(
                        grantee = bugcrowd_client.models.single_relationship.SingleRelationship(
                            links = bugcrowd_client.models.single_relationship_links.SingleRelationshipLinks(
                                related = bugcrowd_client.models.single_relationship_links_related.SingleRelationshipLinks_related(
                                    href = '', ), ), 
                            data = bugcrowd_client.models.basic_object.BasicObject(
                                id = '', 
                                type = '', ), ), 
                        resource = bugcrowd_client.models.single_relationship.SingleRelationship(
                            links = bugcrowd_client.models.single_relationship_links.SingleRelationshipLinks(
                                related = bugcrowd_client.models.single_relationship_links_related.SingleRelationshipLinks_related(
                                    href = '', ), ), 
                            data = bugcrowd_client.models.basic_object.BasicObject(
                                id = '', 
                                type = '', ), ), ), ),
        )
        """

    def testCreateAccessGrantResponse(self):
        """Test CreateAccessGrantResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
