# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.update_customer_asset_request_data import UpdateCustomerAssetRequestData

class TestUpdateCustomerAssetRequestData(unittest.TestCase):
    """UpdateCustomerAssetRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCustomerAssetRequestData:
        """Test UpdateCustomerAssetRequestData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCustomerAssetRequestData`
        """
        model = UpdateCustomerAssetRequestData()
        if include_optional:
            return UpdateCustomerAssetRequestData(
                type = 'customer_asset',
                attributes = bugcrowd_client.models.update_customer_asset_request_data_attributes.UpdateCustomerAssetRequest_data_attributes(
                    name = '', 
                    type = 'ip_address', 
                    description = '', 
                    host_name = 'example.bugcrowd.com', 
                    port_list = [3000,3001,8000], 
                    ip_address = ["192.168.5.1","192.178.7.8/24"], 
                    approved = True, 
                    tags = {"cpe":"cpe:2.3:a:1024cms:1024_cms:1.4.1:*:*:*:*:*:*:*","cve":["CVE-2022-4258","CVE-2014-1122"],"additional":["javascript","java","golang"]}, ),
                relationships = bugcrowd_client.models.update_customer_asset_request_data_relationships.UpdateCustomerAssetRequest_data_relationships(
                    organization = bugcrowd_client.models.organization_nullable.OrganizationNullable(
                        data = bugcrowd_client.models.organization_nullable_data.OrganizationNullable_data(
                            id = '', 
                            type = 'organization', ), ), )
            )
        else:
            return UpdateCustomerAssetRequestData(
                type = 'customer_asset',
                attributes = bugcrowd_client.models.update_customer_asset_request_data_attributes.UpdateCustomerAssetRequest_data_attributes(
                    name = '', 
                    type = 'ip_address', 
                    description = '', 
                    host_name = 'example.bugcrowd.com', 
                    port_list = [3000,3001,8000], 
                    ip_address = ["192.168.5.1","192.178.7.8/24"], 
                    approved = True, 
                    tags = {"cpe":"cpe:2.3:a:1024cms:1024_cms:1.4.1:*:*:*:*:*:*:*","cve":["CVE-2022-4258","CVE-2014-1122"],"additional":["javascript","java","golang"]}, ),
        )
        """

    def testUpdateCustomerAssetRequestData(self):
        """Test UpdateCustomerAssetRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
