# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.link_external_issue_request import LinkExternalIssueRequest

class TestLinkExternalIssueRequest(unittest.TestCase):
    """LinkExternalIssueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkExternalIssueRequest:
        """Test LinkExternalIssueRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkExternalIssueRequest`
        """
        model = LinkExternalIssueRequest()
        if include_optional:
            return LinkExternalIssueRequest(
                data = bugcrowd_client.models.link_external_issue_request_data.LinkExternalIssueRequest_data(
                    type = 'external_issue', 
                    attributes = bugcrowd_client.models.link_external_issue_request_data_attributes.LinkExternalIssueRequest_data_attributes(
                        remote_id = '', ), 
                    relationships = bugcrowd_client.models.link_external_issue_request_data_relationships.LinkExternalIssueRequest_data_relationships(
                        resource = bugcrowd_client.models.submission_nullable.SubmissionNullable(
                            data = bugcrowd_client.models.submission_nullable_data.SubmissionNullable_data(
                                id = '', 
                                type = 'submission', ), ), 
                        integration = bugcrowd_client.models.link_external_issue_request_data_relationships_integration.LinkExternalIssueRequest_data_relationships_integration(
                            data = bugcrowd_client.models.link_external_issue_request_data_relationships_integration_data.LinkExternalIssueRequest_data_relationships_integration_data(
                                type = 'jira_integration', 
                                id = '', ), ), ), )
            )
        else:
            return LinkExternalIssueRequest(
                data = bugcrowd_client.models.link_external_issue_request_data.LinkExternalIssueRequest_data(
                    type = 'external_issue', 
                    attributes = bugcrowd_client.models.link_external_issue_request_data_attributes.LinkExternalIssueRequest_data_attributes(
                        remote_id = '', ), 
                    relationships = bugcrowd_client.models.link_external_issue_request_data_relationships.LinkExternalIssueRequest_data_relationships(
                        resource = bugcrowd_client.models.submission_nullable.SubmissionNullable(
                            data = bugcrowd_client.models.submission_nullable_data.SubmissionNullable_data(
                                id = '', 
                                type = 'submission', ), ), 
                        integration = bugcrowd_client.models.link_external_issue_request_data_relationships_integration.LinkExternalIssueRequest_data_relationships_integration(
                            data = bugcrowd_client.models.link_external_issue_request_data_relationships_integration_data.LinkExternalIssueRequest_data_relationships_integration_data(
                                type = 'jira_integration', 
                                id = '', ), ), ), ),
        )
        """

    def testLinkExternalIssueRequest(self):
        """Test LinkExternalIssueRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
