# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.organization_or_program_roles_enum import OrganizationOrProgramRolesEnum

class TestOrganizationOrProgramRolesEnum(unittest.TestCase):
    """OrganizationOrProgramRolesEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationOrProgramRolesEnum(self):
        """Test OrganizationOrProgramRolesEnum"""
        # inst = OrganizationOrProgramRolesEnum()

if __name__ == '__main__':
    unittest.main()
