# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.cvss_vector_not_nullable import CvssVectorNotNullable

class TestCvssVectorNotNullable(unittest.TestCase):
    """CvssVectorNotNullable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CvssVectorNotNullable:
        """Test CvssVectorNotNullable
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CvssVectorNotNullable`
        """
        model = CvssVectorNotNullable()
        if include_optional:
            return CvssVectorNotNullable(
                data = bugcrowd_client.models.cvss_vector_not_nullable_data.CvssVectorNotNullable_data(
                    id = '', 
                    type = 'cvss_vector', )
            )
        else:
            return CvssVectorNotNullable(
                data = bugcrowd_client.models.cvss_vector_not_nullable_data.CvssVectorNotNullable_data(
                    id = '', 
                    type = 'cvss_vector', ),
        )
        """

    def testCvssVectorNotNullable(self):
        """Test CvssVectorNotNullable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
