# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.create_access_invitation_request_included_inner import CreateAccessInvitationRequestIncludedInner

class TestCreateAccessInvitationRequestIncludedInner(unittest.TestCase):
    """CreateAccessInvitationRequestIncludedInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccessInvitationRequestIncludedInner:
        """Test CreateAccessInvitationRequestIncludedInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccessInvitationRequestIncludedInner`
        """
        model = CreateAccessInvitationRequestIncludedInner()
        if include_optional:
            return CreateAccessInvitationRequestIncludedInner(
                type = 'resource_role',
                attributes = bugcrowd_client.models.create_access_grant_request_data_attributes.CreateAccessGrantRequest_data_attributes(
                    role = 'owner', ),
                relationships = bugcrowd_client.models.create_access_invitation_request_included_inner_relationships.CreateAccessInvitationRequest_included_inner_relationships(
                    resource = bugcrowd_client.models.create_access_invitation_request_included_inner_relationships_resource.CreateAccessInvitationRequest_included_inner_relationships_resource(
                        data = bugcrowd_client.models.create_access_invitation_request_included_inner_relationships_resource_data.CreateAccessInvitationRequest_included_inner_relationships_resource_data(
                            type = 'organization', 
                            id = '', ), ), )
            )
        else:
            return CreateAccessInvitationRequestIncludedInner(
                type = 'resource_role',
                attributes = bugcrowd_client.models.create_access_grant_request_data_attributes.CreateAccessGrantRequest_data_attributes(
                    role = 'owner', ),
                relationships = bugcrowd_client.models.create_access_invitation_request_included_inner_relationships.CreateAccessInvitationRequest_included_inner_relationships(
                    resource = bugcrowd_client.models.create_access_invitation_request_included_inner_relationships_resource.CreateAccessInvitationRequest_included_inner_relationships_resource(
                        data = bugcrowd_client.models.create_access_invitation_request_included_inner_relationships_resource_data.CreateAccessInvitationRequest_included_inner_relationships_resource_data(
                            type = 'organization', 
                            id = '', ), ), ),
        )
        """

    def testCreateAccessInvitationRequestIncludedInner(self):
        """Test CreateAccessInvitationRequestIncludedInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
