# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.scheduled_crowd_member_include_response_inner import ScheduledCrowdMemberIncludeResponseInner

class TestScheduledCrowdMemberIncludeResponseInner(unittest.TestCase):
    """ScheduledCrowdMemberIncludeResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledCrowdMemberIncludeResponseInner:
        """Test ScheduledCrowdMemberIncludeResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledCrowdMemberIncludeResponseInner`
        """
        model = ScheduledCrowdMemberIncludeResponseInner()
        if include_optional:
            return ScheduledCrowdMemberIncludeResponseInner(
                id = '',
                type = 'user',
                attributes = bugcrowd_client.models.program_docusign_user_attributes.ProgramDocusignUser_attributes(
                    id = '', 
                    status = '', 
                    approved_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_signed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                relationships = bugcrowd_client.models.user_relationships.User_relationships(
                    credentials = bugcrowd_client.models.many_relationship.ManyRelationship(
                        links = bugcrowd_client.models.many_relationship_links.ManyRelationshipLinks(
                            related = bugcrowd_client.models.many_relationship_links_related.ManyRelationshipLinks_related(
                                href = '', 
                                meta = bugcrowd_client.models.relationship_count_meta_data.RelationshipCountMetaData(
                                    count = 56, 
                                    total_hits = 56, ), ), ), 
                        data = [
                            bugcrowd_client.models.basic_object.BasicObject(
                                id = '', 
                                type = '', )
                            ], ), 
                    program_docusign_users = bugcrowd_client.models.many_relationship.ManyRelationship(
                        links = bugcrowd_client.models.many_relationship_links.ManyRelationshipLinks(
                            related = bugcrowd_client.models.many_relationship_links_related.ManyRelationshipLinks_related(
                                href = '', ), ), 
                        data = [
                            bugcrowd_client.models.basic_object.BasicObject(
                                id = '', 
                                type = '', )
                            ], ), ),
                links = bugcrowd_client.models.self_link.SelfLink(
                    self = '', )
            )
        else:
            return ScheduledCrowdMemberIncludeResponseInner(
                id = '',
                type = 'user',
        )
        """

    def testScheduledCrowdMemberIncludeResponseInner(self):
        """Test ScheduledCrowdMemberIncludeResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
