# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.create_access_grant_request_data import CreateAccessGrantRequestData

class TestCreateAccessGrantRequestData(unittest.TestCase):
    """CreateAccessGrantRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccessGrantRequestData:
        """Test CreateAccessGrantRequestData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccessGrantRequestData`
        """
        model = CreateAccessGrantRequestData()
        if include_optional:
            return CreateAccessGrantRequestData(
                type = 'access_grant',
                attributes = bugcrowd_client.models.create_access_grant_request_data_attributes.CreateAccessGrantRequest_data_attributes(
                    role = 'owner', ),
                relationships = {"grantee":{"data":{"id":{"$ref":"#/general_helpers/ValidUUID"},"type":"identity"}},"resource":{"data":{"id":{"$ref":"#/general_helpers/ValidUUID"},"type":"organization"}}}
            )
        else:
            return CreateAccessGrantRequestData(
                type = 'access_grant',
                attributes = bugcrowd_client.models.create_access_grant_request_data_attributes.CreateAccessGrantRequest_data_attributes(
                    role = 'owner', ),
                relationships = {"grantee":{"data":{"id":{"$ref":"#/general_helpers/ValidUUID"},"type":"identity"}},"resource":{"data":{"id":{"$ref":"#/general_helpers/ValidUUID"},"type":"organization"}}},
        )
        """

    def testCreateAccessGrantRequestData(self):
        """Test CreateAccessGrantRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
