# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bugcrowd_client.models.create_access_grant_request_data_relationships import CreateAccessGrantRequestDataRelationships

class TestCreateAccessGrantRequestDataRelationships(unittest.TestCase):
    """CreateAccessGrantRequestDataRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAccessGrantRequestDataRelationships:
        """Test CreateAccessGrantRequestDataRelationships
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAccessGrantRequestDataRelationships`
        """
        model = CreateAccessGrantRequestDataRelationships()
        if include_optional:
            return CreateAccessGrantRequestDataRelationships(
                grantee = bugcrowd_client.models.identity_not_nullable.IdentityNotNullable(
                    data = bugcrowd_client.models.identity_not_nullable_data.IdentityNotNullable_data(
                        id = '', 
                        type = 'identity', ), ),
                resource = bugcrowd_client.models.create_access_grant_request_data_relationships_resource.CreateAccessGrantRequest_data_relationships_resource(
                    data = bugcrowd_client.models.create_access_grant_request_data_relationships_resource_data.CreateAccessGrantRequest_data_relationships_resource_data(
                        type = 'organization', 
                        id = '', ), )
            )
        else:
            return CreateAccessGrantRequestDataRelationships(
                grantee = bugcrowd_client.models.identity_not_nullable.IdentityNotNullable(
                    data = bugcrowd_client.models.identity_not_nullable_data.IdentityNotNullable_data(
                        id = '', 
                        type = 'identity', ), ),
                resource = bugcrowd_client.models.create_access_grant_request_data_relationships_resource.CreateAccessGrantRequest_data_relationships_resource(
                    data = bugcrowd_client.models.create_access_grant_request_data_relationships_resource_data.CreateAccessGrantRequest_data_relationships_resource_data(
                        type = 'organization', 
                        id = '', ), ),
        )
        """

    def testCreateAccessGrantRequestDataRelationships(self):
        """Test CreateAccessGrantRequestDataRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
