# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateRewardRangeRequestDataAttributes(BaseModel):
    """
    CreateRewardRangeRequestDataAttributes
    """ # noqa: E501
    p1_max_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p1_min_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p2_max_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p2_min_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p3_max_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p3_min_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p4_max_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p4_min_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p5_max_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    p5_min_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    program_max_cents: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    __properties: ClassVar[List[str]] = ["p1_max_cents", "p1_min_cents", "p2_max_cents", "p2_min_cents", "p3_max_cents", "p3_min_cents", "p4_max_cents", "p4_min_cents", "p5_max_cents", "p5_min_cents", "program_max_cents"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateRewardRangeRequestDataAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if p1_max_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p1_max_cents is None and "p1_max_cents" in self.model_fields_set:
            _dict['p1_max_cents'] = None

        # set to None if p1_min_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p1_min_cents is None and "p1_min_cents" in self.model_fields_set:
            _dict['p1_min_cents'] = None

        # set to None if p2_max_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p2_max_cents is None and "p2_max_cents" in self.model_fields_set:
            _dict['p2_max_cents'] = None

        # set to None if p2_min_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p2_min_cents is None and "p2_min_cents" in self.model_fields_set:
            _dict['p2_min_cents'] = None

        # set to None if p3_max_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p3_max_cents is None and "p3_max_cents" in self.model_fields_set:
            _dict['p3_max_cents'] = None

        # set to None if p3_min_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p3_min_cents is None and "p3_min_cents" in self.model_fields_set:
            _dict['p3_min_cents'] = None

        # set to None if p4_max_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p4_max_cents is None and "p4_max_cents" in self.model_fields_set:
            _dict['p4_max_cents'] = None

        # set to None if p4_min_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p4_min_cents is None and "p4_min_cents" in self.model_fields_set:
            _dict['p4_min_cents'] = None

        # set to None if p5_max_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p5_max_cents is None and "p5_max_cents" in self.model_fields_set:
            _dict['p5_max_cents'] = None

        # set to None if p5_min_cents (nullable) is None
        # and model_fields_set contains the field
        if self.p5_min_cents is None and "p5_min_cents" in self.model_fields_set:
            _dict['p5_min_cents'] = None

        # set to None if program_max_cents (nullable) is None
        # and model_fields_set contains the field
        if self.program_max_cents is None and "program_max_cents" in self.model_fields_set:
            _dict['program_max_cents'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateRewardRangeRequestDataAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "p1_max_cents": obj.get("p1_max_cents"),
            "p1_min_cents": obj.get("p1_min_cents"),
            "p2_max_cents": obj.get("p2_max_cents"),
            "p2_min_cents": obj.get("p2_min_cents"),
            "p3_max_cents": obj.get("p3_max_cents"),
            "p3_min_cents": obj.get("p3_min_cents"),
            "p4_max_cents": obj.get("p4_max_cents"),
            "p4_min_cents": obj.get("p4_min_cents"),
            "p5_max_cents": obj.get("p5_max_cents"),
            "p5_min_cents": obj.get("p5_min_cents"),
            "program_max_cents": obj.get("program_max_cents")
        })
        return _obj


