# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CustomerAssetAttributesTags(BaseModel):
    """
    An object which describes the tags associated with the asset. The categories are  `cve`- A list of Common Vulnerabilities and Exposures tags.  `cpe`- A Common Platform Enumeration tag which abides by the standard of the CPE Version.  `additional`- A list of additional tags which help in describing the asset. 
    """ # noqa: E501
    cpe: Optional[StrictStr] = Field(default=None, description="A Common Platform Enumeration tag. The CPE needs to abide by the standard of the CPE Version 2.3 was released by the U.S. National Institute of Standards and Technology (NIST) in August 2011.  Schema for this `cpe:<cpe_version>:<part>:<vendor>:<product>:<version>:<update>:<edition>:<language>:<sw_edition>:<target_sw>:<target_hw>:<other>` ")
    cve: Optional[List[StrictStr]] = Field(default=None, description="Indicates a list of Common Vulnerabilities and Exposures tags.  These are usually CVE IDs and can have four (4) or more digits in the sequence number portion of the ID.  For example, CVE-YYYY-NNNN with 4 digits in the sequence number, CVE-YYYY-NNNNN with 5 digits in the sequence number, CVE-YYYY-NNNNNNN with 7 digits in the sequence number, and so on. ")
    additional: Optional[List[StrictStr]] = Field(default=None, description="A list of additional tags or user defined custom tags which help in describing the asset.")
    __properties: ClassVar[List[str]] = ["cpe", "cve", "additional"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CustomerAssetAttributesTags from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CustomerAssetAttributesTags from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cpe": obj.get("cpe"),
            "cve": obj.get("cve"),
            "additional": obj.get("additional")
        })
        return _obj


