# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import io
import warnings

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Dict, List, Optional, Tuple, Union, Any

try:
    from typing import Annotated
except ImportError:
    from typing_extensions import Annotated

from pydantic import Field
from typing_extensions import Annotated
from pydantic import StrictStr, field_validator

from typing import List, Optional

from bugcrowd_client.models.create_monetary_reward_request import CreateMonetaryRewardRequest
from bugcrowd_client.models.create_monetary_reward_response import CreateMonetaryRewardResponse
from bugcrowd_client.models.get_monetary_reward_response import GetMonetaryRewardResponse
from bugcrowd_client.models.update_monetary_reward_request import UpdateMonetaryRewardRequest
from bugcrowd_client.models.update_monetary_reward_response import UpdateMonetaryRewardResponse

from bugcrowd_client.api_client import ApiClient
from bugcrowd_client.api_response import ApiResponse
from bugcrowd_client.rest import RESTResponseType


class MonetaryRewardResourceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_monetary_reward(
        self,
        create_monetary_reward_request: Annotated[CreateMonetaryRewardRequest, Field(description="A monetary reward resource with a submission relationship.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CreateMonetaryRewardResponse:
        """Create reward

        Create a new monetary reward for a submission.

        :param create_monetary_reward_request: A monetary reward resource with a submission relationship. (required)
        :type create_monetary_reward_request: CreateMonetaryRewardRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_monetary_reward_serialize(
            create_monetary_reward_request=create_monetary_reward_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CreateMonetaryRewardResponse",
            '400': "ErrorContent",
            '403': "ErrorContent",
            '404': "ErrorContent",
            '409': "ErrorContent",
            '422': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_monetary_reward_with_http_info(
        self,
        create_monetary_reward_request: Annotated[CreateMonetaryRewardRequest, Field(description="A monetary reward resource with a submission relationship.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CreateMonetaryRewardResponse]:
        """Create reward

        Create a new monetary reward for a submission.

        :param create_monetary_reward_request: A monetary reward resource with a submission relationship. (required)
        :type create_monetary_reward_request: CreateMonetaryRewardRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_monetary_reward_serialize(
            create_monetary_reward_request=create_monetary_reward_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CreateMonetaryRewardResponse",
            '400': "ErrorContent",
            '403': "ErrorContent",
            '404': "ErrorContent",
            '409': "ErrorContent",
            '422': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_monetary_reward_without_preload_content(
        self,
        create_monetary_reward_request: Annotated[CreateMonetaryRewardRequest, Field(description="A monetary reward resource with a submission relationship.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create reward

        Create a new monetary reward for a submission.

        :param create_monetary_reward_request: A monetary reward resource with a submission relationship. (required)
        :type create_monetary_reward_request: CreateMonetaryRewardRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_monetary_reward_serialize(
            create_monetary_reward_request=create_monetary_reward_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "CreateMonetaryRewardResponse",
            '400': "ErrorContent",
            '403': "ErrorContent",
            '404': "ErrorContent",
            '409': "ErrorContent",
            '422': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_monetary_reward_serialize(
        self,
        create_monetary_reward_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if create_monetary_reward_request is not None:
            _body_params = create_monetary_reward_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/vnd.bugcrowd.v4+json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/vnd.bugcrowd.v4+json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'tokenAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/monetary_rewards',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_monetary_reward(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_identity: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `identity` resources. If not provided, all fields will be returned")] = None,
        fields_monetary_reward: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=14)]], Field(description="Limit fields for `monetary_reward` resources. If not provided, all fields will be returned")] = None,
        fields_payment: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `payment` resources. If not provided, all fields will be returned")] = None,
        fields_submission: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=35)]], Field(description="Limit fields for `submission` resources. If not provided, all fields will be returned")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetMonetaryRewardResponse:
        """Fetch reward

        Returns a single monetary reward by UUID.

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_identity: Limit fields for `identity` resources. If not provided, all fields will be returned
        :type fields_identity: List[str]
        :param fields_monetary_reward: Limit fields for `monetary_reward` resources. If not provided, all fields will be returned
        :type fields_monetary_reward: List[str]
        :param fields_payment: Limit fields for `payment` resources. If not provided, all fields will be returned
        :type fields_payment: List[str]
        :param fields_submission: Limit fields for `submission` resources. If not provided, all fields will be returned
        :type fields_submission: List[str]
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_monetary_reward_serialize(
            id=id,
            bugcrowd_version=bugcrowd_version,
            fields_identity=fields_identity,
            fields_monetary_reward=fields_monetary_reward,
            fields_payment=fields_payment,
            fields_submission=fields_submission,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetMonetaryRewardResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_monetary_reward_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_identity: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `identity` resources. If not provided, all fields will be returned")] = None,
        fields_monetary_reward: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=14)]], Field(description="Limit fields for `monetary_reward` resources. If not provided, all fields will be returned")] = None,
        fields_payment: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `payment` resources. If not provided, all fields will be returned")] = None,
        fields_submission: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=35)]], Field(description="Limit fields for `submission` resources. If not provided, all fields will be returned")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetMonetaryRewardResponse]:
        """Fetch reward

        Returns a single monetary reward by UUID.

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_identity: Limit fields for `identity` resources. If not provided, all fields will be returned
        :type fields_identity: List[str]
        :param fields_monetary_reward: Limit fields for `monetary_reward` resources. If not provided, all fields will be returned
        :type fields_monetary_reward: List[str]
        :param fields_payment: Limit fields for `payment` resources. If not provided, all fields will be returned
        :type fields_payment: List[str]
        :param fields_submission: Limit fields for `submission` resources. If not provided, all fields will be returned
        :type fields_submission: List[str]
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_monetary_reward_serialize(
            id=id,
            bugcrowd_version=bugcrowd_version,
            fields_identity=fields_identity,
            fields_monetary_reward=fields_monetary_reward,
            fields_payment=fields_payment,
            fields_submission=fields_submission,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetMonetaryRewardResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_monetary_reward_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_identity: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `identity` resources. If not provided, all fields will be returned")] = None,
        fields_monetary_reward: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=14)]], Field(description="Limit fields for `monetary_reward` resources. If not provided, all fields will be returned")] = None,
        fields_payment: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `payment` resources. If not provided, all fields will be returned")] = None,
        fields_submission: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=35)]], Field(description="Limit fields for `submission` resources. If not provided, all fields will be returned")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Fetch reward

        Returns a single monetary reward by UUID.

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_identity: Limit fields for `identity` resources. If not provided, all fields will be returned
        :type fields_identity: List[str]
        :param fields_monetary_reward: Limit fields for `monetary_reward` resources. If not provided, all fields will be returned
        :type fields_monetary_reward: List[str]
        :param fields_payment: Limit fields for `payment` resources. If not provided, all fields will be returned
        :type fields_payment: List[str]
        :param fields_submission: Limit fields for `submission` resources. If not provided, all fields will be returned
        :type fields_submission: List[str]
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_monetary_reward_serialize(
            id=id,
            bugcrowd_version=bugcrowd_version,
            fields_identity=fields_identity,
            fields_monetary_reward=fields_monetary_reward,
            fields_payment=fields_payment,
            fields_submission=fields_submission,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetMonetaryRewardResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_monetary_reward_serialize(
        self,
        id,
        bugcrowd_version,
        fields_identity,
        fields_monetary_reward,
        fields_payment,
        fields_submission,
        include,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            'fields[identity]': 'csv',
            'fields[monetary_reward]': 'csv',
            'fields[payment]': 'csv',
            'fields[submission]': 'csv',
            'include': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if fields_identity is not None:
            
            _query_params.append(('fields[identity]', fields_identity))
            
        if fields_monetary_reward is not None:
            
            _query_params.append(('fields[monetary_reward]', fields_monetary_reward))
            
        if fields_payment is not None:
            
            _query_params.append(('fields[payment]', fields_payment))
            
        if fields_submission is not None:
            
            _query_params.append(('fields[submission]', fields_submission))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        # process the header parameters
        if bugcrowd_version is not None:
            _header_params['Bugcrowd-Version'] = bugcrowd_version
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/vnd.bugcrowd.v4+json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'tokenAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/monetary_rewards/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_monetary_reward(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        update_monetary_reward_request: Annotated[UpdateMonetaryRewardRequest, Field(description="Update reward")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> UpdateMonetaryRewardResponse:
        """Update reward

        Cancel a monetary reward and provide a reason

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param update_monetary_reward_request: Update reward (required)
        :type update_monetary_reward_request: UpdateMonetaryRewardRequest
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_monetary_reward_serialize(
            id=id,
            update_monetary_reward_request=update_monetary_reward_request,
            bugcrowd_version=bugcrowd_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateMonetaryRewardResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
            '422': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_monetary_reward_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        update_monetary_reward_request: Annotated[UpdateMonetaryRewardRequest, Field(description="Update reward")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[UpdateMonetaryRewardResponse]:
        """Update reward

        Cancel a monetary reward and provide a reason

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param update_monetary_reward_request: Update reward (required)
        :type update_monetary_reward_request: UpdateMonetaryRewardRequest
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_monetary_reward_serialize(
            id=id,
            update_monetary_reward_request=update_monetary_reward_request,
            bugcrowd_version=bugcrowd_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateMonetaryRewardResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
            '422': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_monetary_reward_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        update_monetary_reward_request: Annotated[UpdateMonetaryRewardRequest, Field(description="Update reward")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update reward

        Cancel a monetary reward and provide a reason

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param update_monetary_reward_request: Update reward (required)
        :type update_monetary_reward_request: UpdateMonetaryRewardRequest
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_monetary_reward_serialize(
            id=id,
            update_monetary_reward_request=update_monetary_reward_request,
            bugcrowd_version=bugcrowd_version,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateMonetaryRewardResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
            '422': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_monetary_reward_serialize(
        self,
        id,
        update_monetary_reward_request,
        bugcrowd_version,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        if bugcrowd_version is not None:
            _header_params['Bugcrowd-Version'] = bugcrowd_version
        # process the form parameters
        # process the body parameter
        if update_monetary_reward_request is not None:
            _body_params = update_monetary_reward_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/vnd.bugcrowd.v4+json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/vnd.bugcrowd.v4+json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'tokenAuth'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/monetary_rewards/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


