# coding: utf-8

"""
    Bugcrowd REST API

    This is Bugcrowd's primary REST API and follows the [JSON API specification](https://jsonapi.org/format/).  For more information on how to get started check out the [usage documentation](https://docs.bugcrowd.com/api/usage/) 

    The version of the OpenAPI document: 2024-01-11
    Contact: support@bugcrowd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import io
import warnings

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Dict, List, Optional, Tuple, Union, Any

try:
    from typing import Annotated
except ImportError:
    from typing_extensions import Annotated

from pydantic import Field
from typing_extensions import Annotated
from pydantic import StrictStr, field_validator

from typing import List, Optional

from bugcrowd_client.models.get_organization_response import GetOrganizationResponse
from bugcrowd_client.models.list_organizations_response import ListOrganizationsResponse

from bugcrowd_client.api_client import ApiClient
from bugcrowd_client.api_response import ApiResponse
from bugcrowd_client.rest import RESTResponseType


class OrganizationResourceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_organization(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_organization: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `organization` resources. If not provided, all fields will be returned")] = None,
        fields_program: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `program` resources. If not provided, all fields will be returned")] = None,
        fields_target: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=4)]], Field(description="Limit fields for `target` resources. If not provided, all fields will be returned")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetOrganizationResponse:
        """Fetch organization

        Returns a single organization by UUID.

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_organization: Limit fields for `organization` resources. If not provided, all fields will be returned
        :type fields_organization: List[str]
        :param fields_program: Limit fields for `program` resources. If not provided, all fields will be returned
        :type fields_program: List[str]
        :param fields_target: Limit fields for `target` resources. If not provided, all fields will be returned
        :type fields_target: List[str]
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_organization_serialize(
            id=id,
            bugcrowd_version=bugcrowd_version,
            fields_organization=fields_organization,
            fields_program=fields_program,
            fields_target=fields_target,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetOrganizationResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_organization_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_organization: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `organization` resources. If not provided, all fields will be returned")] = None,
        fields_program: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `program` resources. If not provided, all fields will be returned")] = None,
        fields_target: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=4)]], Field(description="Limit fields for `target` resources. If not provided, all fields will be returned")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetOrganizationResponse]:
        """Fetch organization

        Returns a single organization by UUID.

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_organization: Limit fields for `organization` resources. If not provided, all fields will be returned
        :type fields_organization: List[str]
        :param fields_program: Limit fields for `program` resources. If not provided, all fields will be returned
        :type fields_program: List[str]
        :param fields_target: Limit fields for `target` resources. If not provided, all fields will be returned
        :type fields_target: List[str]
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_organization_serialize(
            id=id,
            bugcrowd_version=bugcrowd_version,
            fields_organization=fields_organization,
            fields_program=fields_program,
            fields_target=fields_target,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetOrganizationResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_organization_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="The ID of the resource in uuid format")],
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_organization: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `organization` resources. If not provided, all fields will be returned")] = None,
        fields_program: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `program` resources. If not provided, all fields will be returned")] = None,
        fields_target: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=4)]], Field(description="Limit fields for `target` resources. If not provided, all fields will be returned")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Fetch organization

        Returns a single organization by UUID.

        :param id: The ID of the resource in uuid format (required)
        :type id: str
        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_organization: Limit fields for `organization` resources. If not provided, all fields will be returned
        :type fields_organization: List[str]
        :param fields_program: Limit fields for `program` resources. If not provided, all fields will be returned
        :type fields_program: List[str]
        :param fields_target: Limit fields for `target` resources. If not provided, all fields will be returned
        :type fields_target: List[str]
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_organization_serialize(
            id=id,
            bugcrowd_version=bugcrowd_version,
            fields_organization=fields_organization,
            fields_program=fields_program,
            fields_target=fields_target,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetOrganizationResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_organization_serialize(
        self,
        id,
        bugcrowd_version,
        fields_organization,
        fields_program,
        fields_target,
        include,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            'fields[organization]': 'csv',
            'fields[program]': 'csv',
            'fields[target]': 'csv',
            'include': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if fields_organization is not None:
            
            _query_params.append(('fields[organization]', fields_organization))
            
        if fields_program is not None:
            
            _query_params.append(('fields[program]', fields_program))
            
        if fields_target is not None:
            
            _query_params.append(('fields[target]', fields_target))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        # process the header parameters
        if bugcrowd_version is not None:
            _header_params['Bugcrowd-Version'] = bugcrowd_version
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/vnd.bugcrowd.v4+json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'tokenAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/organizations/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_organizations(
        self,
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_organization: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `organization` resources. If not provided, all fields will be returned")] = None,
        fields_program: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `program` resources. If not provided, all fields will be returned")] = None,
        fields_target: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=4)]], Field(description="Limit fields for `target` resources. If not provided, all fields will be returned")] = None,
        page_limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=0)]], Field(description="Limit parameter for pagination (default page[limit] = 25)")] = None,
        page_offset: Annotated[Optional[Annotated[int, Field(le=9900, strict=True, ge=0)]], Field(description="Offset parameter for pagination (default page[offset] = 0 == first page)")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        sort: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Sorting options")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListOrganizationsResponse:
        """Index organizations

        Returns a list of organizations belonging to the user.

        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_organization: Limit fields for `organization` resources. If not provided, all fields will be returned
        :type fields_organization: List[str]
        :param fields_program: Limit fields for `program` resources. If not provided, all fields will be returned
        :type fields_program: List[str]
        :param fields_target: Limit fields for `target` resources. If not provided, all fields will be returned
        :type fields_target: List[str]
        :param page_limit: Limit parameter for pagination (default page[limit] = 25)
        :type page_limit: int
        :param page_offset: Offset parameter for pagination (default page[offset] = 0 == first page)
        :type page_offset: int
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param sort: Sorting options
        :type sort: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_organizations_serialize(
            bugcrowd_version=bugcrowd_version,
            fields_organization=fields_organization,
            fields_program=fields_program,
            fields_target=fields_target,
            page_limit=page_limit,
            page_offset=page_offset,
            include=include,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListOrganizationsResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_organizations_with_http_info(
        self,
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_organization: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `organization` resources. If not provided, all fields will be returned")] = None,
        fields_program: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `program` resources. If not provided, all fields will be returned")] = None,
        fields_target: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=4)]], Field(description="Limit fields for `target` resources. If not provided, all fields will be returned")] = None,
        page_limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=0)]], Field(description="Limit parameter for pagination (default page[limit] = 25)")] = None,
        page_offset: Annotated[Optional[Annotated[int, Field(le=9900, strict=True, ge=0)]], Field(description="Offset parameter for pagination (default page[offset] = 0 == first page)")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        sort: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Sorting options")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListOrganizationsResponse]:
        """Index organizations

        Returns a list of organizations belonging to the user.

        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_organization: Limit fields for `organization` resources. If not provided, all fields will be returned
        :type fields_organization: List[str]
        :param fields_program: Limit fields for `program` resources. If not provided, all fields will be returned
        :type fields_program: List[str]
        :param fields_target: Limit fields for `target` resources. If not provided, all fields will be returned
        :type fields_target: List[str]
        :param page_limit: Limit parameter for pagination (default page[limit] = 25)
        :type page_limit: int
        :param page_offset: Offset parameter for pagination (default page[offset] = 0 == first page)
        :type page_offset: int
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param sort: Sorting options
        :type sort: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_organizations_serialize(
            bugcrowd_version=bugcrowd_version,
            fields_organization=fields_organization,
            fields_program=fields_program,
            fields_target=fields_target,
            page_limit=page_limit,
            page_offset=page_offset,
            include=include,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListOrganizationsResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_organizations_without_preload_content(
        self,
        bugcrowd_version: Annotated[Optional[StrictStr], Field(description="The request header used to test new API versions before updating the pinned account version")] = None,
        fields_organization: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=3)]], Field(description="Limit fields for `organization` resources. If not provided, all fields will be returned")] = None,
        fields_program: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=5)]], Field(description="Limit fields for `program` resources. If not provided, all fields will be returned")] = None,
        fields_target: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=4)]], Field(description="Limit fields for `target` resources. If not provided, all fields will be returned")] = None,
        page_limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=0)]], Field(description="Limit parameter for pagination (default page[limit] = 25)")] = None,
        page_offset: Annotated[Optional[Annotated[int, Field(le=9900, strict=True, ge=0)]], Field(description="Offset parameter for pagination (default page[offset] = 0 == first page)")] = None,
        include: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Related associations that will be returned as a flat list of objects.")] = None,
        sort: Annotated[Optional[Annotated[List[StrictStr], Field(max_length=2)]], Field(description="Sorting options")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Index organizations

        Returns a list of organizations belonging to the user.

        :param bugcrowd_version: The request header used to test new API versions before updating the pinned account version
        :type bugcrowd_version: str
        :param fields_organization: Limit fields for `organization` resources. If not provided, all fields will be returned
        :type fields_organization: List[str]
        :param fields_program: Limit fields for `program` resources. If not provided, all fields will be returned
        :type fields_program: List[str]
        :param fields_target: Limit fields for `target` resources. If not provided, all fields will be returned
        :type fields_target: List[str]
        :param page_limit: Limit parameter for pagination (default page[limit] = 25)
        :type page_limit: int
        :param page_offset: Offset parameter for pagination (default page[offset] = 0 == first page)
        :type page_offset: int
        :param include: Related associations that will be returned as a flat list of objects.
        :type include: List[str]
        :param sort: Sorting options
        :type sort: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_organizations_serialize(
            bugcrowd_version=bugcrowd_version,
            fields_organization=fields_organization,
            fields_program=fields_program,
            fields_target=fields_target,
            page_limit=page_limit,
            page_offset=page_offset,
            include=include,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListOrganizationsResponse",
            '400': "ErrorContent",
            '404': "ErrorContent",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_organizations_serialize(
        self,
        bugcrowd_version,
        fields_organization,
        fields_program,
        fields_target,
        page_limit,
        page_offset,
        include,
        sort,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            'fields[organization]': 'csv',
            'fields[program]': 'csv',
            'fields[target]': 'csv',
            'include': 'csv',
            'sort': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if fields_organization is not None:
            
            _query_params.append(('fields[organization]', fields_organization))
            
        if fields_program is not None:
            
            _query_params.append(('fields[program]', fields_program))
            
        if fields_target is not None:
            
            _query_params.append(('fields[target]', fields_target))
            
        if page_limit is not None:
            
            _query_params.append(('page[limit]', page_limit))
            
        if page_offset is not None:
            
            _query_params.append(('page[offset]', page_offset))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        # process the header parameters
        if bugcrowd_version is not None:
            _header_params['Bugcrowd-Version'] = bugcrowd_version
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/vnd.bugcrowd.v4+json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'tokenAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/organizations',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


